-- Run in Supabase SQL Editor.
create table if not exists public.shop_settings(
 id bigint primary key default 1, shop_name text not null default 'Bapu Bhai Collection',
 tagline text default '', whatsapp_number text default '', instagram_url text default '',
 instagram_handle text default '', city text default '', hours text default '', updated_at timestamptz default now()
);
insert into public.shop_settings(id,shop_name,tagline,whatsapp_number,instagram_url,instagram_handle,city,hours)
values(1,'Bapu Bhai Collection','Jo Reels mein dekha, seedha WhatsApp pe mangwao.','91XXXXXXXXXX','https://instagram.com/yourshophandle','@yourshophandle','Your City','Mon–Sat, 10am – 8pm')
on conflict(id) do nothing;

create table if not exists public.products(
 id bigint generated by default as identity primary key, name text not null, price numeric not null default 0,
 type text not null default 'kurti', image_url text, sort_order integer not null default 0, created_at timestamptz default now()
);
alter table public.shop_settings enable row level security;
alter table public.products enable row level security;

drop policy if exists "Public can read shop settings" on public.shop_settings;
create policy "Public can read shop settings" on public.shop_settings for select to anon,authenticated using(true);
drop policy if exists "Owner can manage shop settings" on public.shop_settings;
create policy "Owner can manage shop settings" on public.shop_settings for all to authenticated using(true) with check(true);

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products" on public.products for select to anon,authenticated using(true);
drop policy if exists "Owner can manage products" on public.products;
create policy "Owner can manage products" on public.products for all to authenticated using(true) with check(true);

insert into storage.buckets(id,name,public) values('product-images','product-images',true)
on conflict(id) do update set public=true;
drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images" on storage.objects for select to anon,authenticated using(bucket_id='product-images');
drop policy if exists "Owner can upload product images" on storage.objects;
create policy "Owner can upload product images" on storage.objects for insert to authenticated with check(bucket_id='product-images');
drop policy if exists "Owner can update product images" on storage.objects;
create policy "Owner can update product images" on storage.objects for update to authenticated using(bucket_id='product-images') with check(bucket_id='product-images');
drop policy if exists "Owner can delete product images" on storage.objects;
create policy "Owner can delete product images" on storage.objects for delete to authenticated using(bucket_id='product-images');
